[project]
name = "better-tiss-calendar"
version = "0.0.1"
dependencies = [
    "flask>=3.1.0",
    "gunicorn>=23.0.0",
    "icalendar>=6.1.1",
    "requests>=2.32.3",
]
requires-python = ">=3.13"
authors = [{ name = "flofriday" }]
description = "A better TISS calendar"
readme = "README.md"
license = { file = "LICENSE.txt" }

[tool.pytest.ini_options]
testpaths = ["tests"]
pythonpath = ["."]

[tool.coverage.run]
branch = true
source = ["app"]

[tool.ruff.lint]
select = ["E", "F", "UP", "B", "SIM", "I"]

[tool.pyright]
venvPath = "."
venv = ".venv"
exclude = ["venv", ".venv", "**/resources"]

[dependency-groups]
dev = [
    "pytest-mock>=3.14.0",
    "pytest>=8.3.5",
    "pyright>=1.1.394",
    "ruff>=0.11.0",
]
