# A basic action that deploys to the server

name: CI

on: [push]

jobs:
  test:
    runs-on: Ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Set up Python
        run: uv python install

      - name: Install dependencies
        run: uv sync

      - name: Linting
        run: uv run ruff check

      - name: Formatting
        run: uv run ruff format --check

      - name: Typecheck
        run: uv run ty check

      - name: Test with pytest
        run: uv run pytest

  deploy:
    needs: test
    if: ${{ github.ref_name == 'main' }}
    runs-on: ubuntu-latest
    steps:
      - name: deploy on production server
        uses: appleboy/ssh-action@v1.2.1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script_stop: true
          script: |
            cd better-tiss-calendar
            git fetch --all
            git reset --hard origin/main
            npm install
            npx @tailwindcss/cli --minify -i app/templates/template.css -o app/static/style.css
            /home/bettercal/.local/bin/uv sync
            systemctl --user restart bettercal.service
