# A basic action that deploys to the server 

name: CI

on: [push]

jobs:
  deploy:
    if: ${{ github.ref_name == 'main' }}
    runs-on: ubuntu-latest
    steps:
    - name: deploy on production server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script_stop: true
        script: |
          cd better-tiss-calendar
          git pull
          npm install
          npx tailwindcss --minify -i templates/template.css -o static/style.css
          source .venv/bin/activate
          python -m pip install -r requirements.txt
          systemctl --user restart bettercal.service